import{a as f,S,i as a}from"./assets/vendor-BkC4bTqC.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();f.defaults.baseURL="https://pixabay.com/api/";const q="55036572-7370ebd0316836cff88f01645";async function m(t,r){return(await f.get("/",{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),p=document.querySelector(".load-more"),$=new S(".gallery a");function g(t){const r=t.map(s=>`
      <li class="gallery-item">
        <a href="${s.largeImageURL}">
          <img src="${s.webformatURL}" alt="${s.tags}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${s.likes}</p>
          <p><b>Views:</b> ${s.views}</p>
          <p><b>Comments:</b> ${s.comments}</p>
          <p><b>Downloads:</b> ${s.downloads}</p>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",r),$.refresh()}function B(){h.innerHTML=""}function b(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}function v(){p.classList.remove("hidden")}function w(){p.classList.add("hidden")}let i="",l=1,d=0,n=0;const E=document.querySelector("#search-form"),I=document.querySelector(".load-more");E.addEventListener("submit",async t=>{if(t.preventDefault(),i=t.target.elements.search.value.trim(),!!i){B(),w(),l=1,n=0,b();try{const r=await m(i,l);if(d=r.totalHits,n+=r.hits.length,r.hits.length===0){a.error({title:"Error",message:"No images found!"});return}g(r.hits),n<d?v():a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}catch(r){a.error({title:"Error",message:r.message})}finally{L()}}});I.addEventListener("click",async()=>{l+=1,w(),b();try{const t=await m(i,l);n+=t.hits.length,g(t.hits),n>=d?a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}):v(),M()}catch(t){a.error({title:"Error",message:t.message})}finally{L()}});function M(){const{height:t}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
